development:
  adapter: postgresql
  encoding: unicode
  database: prism_dev
  host: localhost
  pool: 5
  timeout: 5000
  username: pguser
  password: pguser

test:
  adapter: postgresql
  encoding: unicode
  database: prism_test
  host: localhost
  pool: 5
  timeout: 5000
  username: pguser
  password: pguser

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
