# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad72940b89449f1ba7a6e92f9cc84eb12eb6ccf3ee311b65cb2dcb9c1bbc746641e1e56c84803998bfb63ece9a6e213cf0185e86185d9bc9bc5cd99b94c944c8

test:
  secret_key_base: 6cbb7c6ddadb8197a56dc6f61321b7a5e7f9ff39b8a47c693fcd506c35e345153c90bfe014b53b566b22b43dad277edf0f7c4423a067240ee6fcd75364c28987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6cbb7c6ddadb8197a56dc6f61321b7a5e7f9ff39b8a47c693fcd506c35e345153c90bfe014b53b566b22b43dad277edf0f7c4423a067240ee6fcd75364c28987
